#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBookShop
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BookShop")]
	public partial class DataBookShopDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertusersShop(usersShop instance);
    partial void UpdateusersShop(usersShop instance);
    partial void DeleteusersShop(usersShop instance);
    partial void InsertbookShop(bookShop instance);
    partial void UpdatebookShop(bookShop instance);
    partial void DeletebookShop(bookShop instance);
    partial void InsertuserBookShop(userBookShop instance);
    partial void UpdateuserBookShop(userBookShop instance);
    partial void DeleteuserBookShop(userBookShop instance);
    #endregion
		
		public DataBookShopDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BookShopConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBookShopDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBookShopDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBookShopDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBookShopDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<usersShop> usersShops
		{
			get
			{
				return this.GetTable<usersShop>();
			}
		}
		
		public System.Data.Linq.Table<bookShop> bookShops
		{
			get
			{
				return this.GetTable<bookShop>();
			}
		}
		
		public System.Data.Linq.Table<userBookShop> userBookShops
		{
			get
			{
				return this.GetTable<userBookShop>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usersShop")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class usersShop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _passWordName;
		
		private string _emailAddress;
		
		private string _phoneNumber;
		
		private string _pathimages;
		
		private System.Nullable<decimal> _bankUser;
		
		private EntitySet<userBookShop> _userBookShops;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpassWordNameChanging(string value);
    partial void OnpassWordNameChanged();
    partial void OnemailAddressChanging(string value);
    partial void OnemailAddressChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OnpathimagesChanging(string value);
    partial void OnpathimagesChanged();
    partial void OnbankUserChanging(System.Nullable<decimal> value);
    partial void OnbankUserChanged();
    #endregion
		
		public usersShop()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(90)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passWordName", DbType="NVarChar(90)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string passWordName
		{
			get
			{
				return this._passWordName;
			}
			set
			{
				if ((this._passWordName != value))
				{
					this.OnpassWordNameChanging(value);
					this.SendPropertyChanging();
					this._passWordName = value;
					this.SendPropertyChanged("passWordName");
					this.OnpassWordNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailAddress", DbType="NVarChar(90) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string emailAddress
		{
			get
			{
				return this._emailAddress;
			}
			set
			{
				if ((this._emailAddress != value))
				{
					this.OnemailAddressChanging(value);
					this.SendPropertyChanging();
					this._emailAddress = value;
					this.SendPropertyChanged("emailAddress");
					this.OnemailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NVarChar(90)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimages", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string pathimages
		{
			get
			{
				return this._pathimages;
			}
			set
			{
				if ((this._pathimages != value))
				{
					this.OnpathimagesChanging(value);
					this.SendPropertyChanging();
					this._pathimages = value;
					this.SendPropertyChanged("pathimages");
					this.OnpathimagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankUser", DbType="Money")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<decimal> bankUser
		{
			get
			{
				return this._bankUser;
			}
			set
			{
				if ((this._bankUser != value))
				{
					this.OnbankUserChanging(value);
					this.SendPropertyChanging();
					this._bankUser = value;
					this.SendPropertyChanged("bankUser");
					this.OnbankUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usersShop_userBookShop", Storage="_userBookShops", ThisKey="emailAddress", OtherKey="emailAddress")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7, EmitDefaultValue=false)]
		public EntitySet<userBookShop> userBookShops
		{
			get
			{
				if ((this.serializing 
							&& (this._userBookShops.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._userBookShops;
			}
			set
			{
				this._userBookShops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_userBookShops(userBookShop entity)
		{
			this.SendPropertyChanging();
			entity.usersShop = this;
		}
		
		private void detach_userBookShops(userBookShop entity)
		{
			this.SendPropertyChanging();
			entity.usersShop = null;
		}
		
		private void Initialize()
		{
			this._userBookShops = new EntitySet<userBookShop>(new Action<userBookShop>(this.attach_userBookShops), new Action<userBookShop>(this.detach_userBookShops));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bookShop")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class bookShop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBook;
		
		private string _nameBook;
		
		private string _authorBook;
		
		private string _category;
		
		private System.Nullable<decimal> _priceBook;
		
		private string _descriptionBook;
		
		private string _pathBook;
		
		private string _pathimages;
		
		private EntitySet<userBookShop> _userBookShops;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBookChanging(int value);
    partial void OnidBookChanged();
    partial void OnnameBookChanging(string value);
    partial void OnnameBookChanged();
    partial void OnauthorBookChanging(string value);
    partial void OnauthorBookChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void OnpriceBookChanging(System.Nullable<decimal> value);
    partial void OnpriceBookChanged();
    partial void OndescriptionBookChanging(string value);
    partial void OndescriptionBookChanged();
    partial void OnpathBookChanging(string value);
    partial void OnpathBookChanged();
    partial void OnpathimagesChanging(string value);
    partial void OnpathimagesChanged();
    #endregion
		
		public bookShop()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBook", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int idBook
		{
			get
			{
				return this._idBook;
			}
			set
			{
				if ((this._idBook != value))
				{
					this.OnidBookChanging(value);
					this.SendPropertyChanging();
					this._idBook = value;
					this.SendPropertyChanged("idBook");
					this.OnidBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameBook", DbType="NVarChar(90)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string nameBook
		{
			get
			{
				return this._nameBook;
			}
			set
			{
				if ((this._nameBook != value))
				{
					this.OnnameBookChanging(value);
					this.SendPropertyChanging();
					this._nameBook = value;
					this.SendPropertyChanged("nameBook");
					this.OnnameBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authorBook", DbType="NVarChar(90)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string authorBook
		{
			get
			{
				return this._authorBook;
			}
			set
			{
				if ((this._authorBook != value))
				{
					this.OnauthorBookChanging(value);
					this.SendPropertyChanging();
					this._authorBook = value;
					this.SendPropertyChanged("authorBook");
					this.OnauthorBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(90)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceBook", DbType="Money")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<decimal> priceBook
		{
			get
			{
				return this._priceBook;
			}
			set
			{
				if ((this._priceBook != value))
				{
					this.OnpriceBookChanging(value);
					this.SendPropertyChanging();
					this._priceBook = value;
					this.SendPropertyChanged("priceBook");
					this.OnpriceBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descriptionBook", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string descriptionBook
		{
			get
			{
				return this._descriptionBook;
			}
			set
			{
				if ((this._descriptionBook != value))
				{
					this.OndescriptionBookChanging(value);
					this.SendPropertyChanging();
					this._descriptionBook = value;
					this.SendPropertyChanged("descriptionBook");
					this.OndescriptionBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathBook", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string pathBook
		{
			get
			{
				return this._pathBook;
			}
			set
			{
				if ((this._pathBook != value))
				{
					this.OnpathBookChanging(value);
					this.SendPropertyChanging();
					this._pathBook = value;
					this.SendPropertyChanged("pathBook");
					this.OnpathBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimages", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string pathimages
		{
			get
			{
				return this._pathimages;
			}
			set
			{
				if ((this._pathimages != value))
				{
					this.OnpathimagesChanging(value);
					this.SendPropertyChanging();
					this._pathimages = value;
					this.SendPropertyChanged("pathimages");
					this.OnpathimagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bookShop_userBookShop", Storage="_userBookShops", ThisKey="idBook", OtherKey="idBook")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9, EmitDefaultValue=false)]
		public EntitySet<userBookShop> userBookShops
		{
			get
			{
				if ((this.serializing 
							&& (this._userBookShops.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._userBookShops;
			}
			set
			{
				this._userBookShops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_userBookShops(userBookShop entity)
		{
			this.SendPropertyChanging();
			entity.bookShop = this;
		}
		
		private void detach_userBookShops(userBookShop entity)
		{
			this.SendPropertyChanging();
			entity.bookShop = null;
		}
		
		private void Initialize()
		{
			this._userBookShops = new EntitySet<userBookShop>(new Action<userBookShop>(this.attach_userBookShops), new Action<userBookShop>(this.detach_userBookShops));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userBookShop")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class userBookShop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUserBookShop;
		
		private string _emailAddress;
		
		private System.Nullable<int> _idBook;
		
		private EntityRef<usersShop> _usersShop;
		
		private EntityRef<bookShop> _bookShop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUserBookShopChanging(int value);
    partial void OnidUserBookShopChanged();
    partial void OnemailAddressChanging(string value);
    partial void OnemailAddressChanged();
    partial void OnidBookChanging(System.Nullable<int> value);
    partial void OnidBookChanged();
    #endregion
		
		public userBookShop()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUserBookShop", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int idUserBookShop
		{
			get
			{
				return this._idUserBookShop;
			}
			set
			{
				if ((this._idUserBookShop != value))
				{
					this.OnidUserBookShopChanging(value);
					this.SendPropertyChanging();
					this._idUserBookShop = value;
					this.SendPropertyChanged("idUserBookShop");
					this.OnidUserBookShopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailAddress", DbType="NVarChar(90)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string emailAddress
		{
			get
			{
				return this._emailAddress;
			}
			set
			{
				if ((this._emailAddress != value))
				{
					if (this._usersShop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailAddressChanging(value);
					this.SendPropertyChanging();
					this._emailAddress = value;
					this.SendPropertyChanged("emailAddress");
					this.OnemailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBook", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> idBook
		{
			get
			{
				return this._idBook;
			}
			set
			{
				if ((this._idBook != value))
				{
					if (this._bookShop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidBookChanging(value);
					this.SendPropertyChanging();
					this._idBook = value;
					this.SendPropertyChanged("idBook");
					this.OnidBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usersShop_userBookShop", Storage="_usersShop", ThisKey="emailAddress", OtherKey="emailAddress", IsForeignKey=true)]
		public usersShop usersShop
		{
			get
			{
				return this._usersShop.Entity;
			}
			set
			{
				usersShop previousValue = this._usersShop.Entity;
				if (((previousValue != value) 
							|| (this._usersShop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usersShop.Entity = null;
						previousValue.userBookShops.Remove(this);
					}
					this._usersShop.Entity = value;
					if ((value != null))
					{
						value.userBookShops.Add(this);
						this._emailAddress = value.emailAddress;
					}
					else
					{
						this._emailAddress = default(string);
					}
					this.SendPropertyChanged("usersShop");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bookShop_userBookShop", Storage="_bookShop", ThisKey="idBook", OtherKey="idBook", IsForeignKey=true)]
		public bookShop bookShop
		{
			get
			{
				return this._bookShop.Entity;
			}
			set
			{
				bookShop previousValue = this._bookShop.Entity;
				if (((previousValue != value) 
							|| (this._bookShop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bookShop.Entity = null;
						previousValue.userBookShops.Remove(this);
					}
					this._bookShop.Entity = value;
					if ((value != null))
					{
						value.userBookShops.Add(this);
						this._idBook = value.idBook;
					}
					else
					{
						this._idBook = default(Nullable<int>);
					}
					this.SendPropertyChanged("bookShop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._usersShop = default(EntityRef<usersShop>);
			this._bookShop = default(EntityRef<bookShop>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
