//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace BookShop.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usersShop", Namespace="http://schemas.datacontract.org/2004/07/ServiceBookShop")]
    public partial class usersShop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordNameField;
        
        private string emailAddressField;
        
        private string phoneNumberField;
        
        private string pathimagesField;
        
        private System.Nullable<decimal> bankUserField;
        
        private System.Collections.ObjectModel.ObservableCollection<BookShop.ServiceReference1.userBookShop> userBookShopsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string passWordName {
            get {
                return this.passWordNameField;
            }
            set {
                if ((object.ReferenceEquals(this.passWordNameField, value) != true)) {
                    this.passWordNameField = value;
                    this.RaisePropertyChanged("passWordName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressField, value) != true)) {
                    this.emailAddressField = value;
                    this.RaisePropertyChanged("emailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string pathimages {
            get {
                return this.pathimagesField;
            }
            set {
                if ((object.ReferenceEquals(this.pathimagesField, value) != true)) {
                    this.pathimagesField = value;
                    this.RaisePropertyChanged("pathimages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> bankUser {
            get {
                return this.bankUserField;
            }
            set {
                if ((this.bankUserField.Equals(value) != true)) {
                    this.bankUserField = value;
                    this.RaisePropertyChanged("bankUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Collections.ObjectModel.ObservableCollection<BookShop.ServiceReference1.userBookShop> userBookShops {
            get {
                return this.userBookShopsField;
            }
            set {
                if ((object.ReferenceEquals(this.userBookShopsField, value) != true)) {
                    this.userBookShopsField = value;
                    this.RaisePropertyChanged("userBookShops");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userBookShop", Namespace="http://schemas.datacontract.org/2004/07/ServiceBookShop")]
    public partial class userBookShop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idUserBookShopField;
        
        private string emailAddressField;
        
        private System.Nullable<int> idBookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUserBookShop {
            get {
                return this.idUserBookShopField;
            }
            set {
                if ((this.idUserBookShopField.Equals(value) != true)) {
                    this.idUserBookShopField = value;
                    this.RaisePropertyChanged("idUserBookShop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressField, value) != true)) {
                    this.emailAddressField = value;
                    this.RaisePropertyChanged("emailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> idBook {
            get {
                return this.idBookField;
            }
            set {
                if ((this.idBookField.Equals(value) != true)) {
                    this.idBookField = value;
                    this.RaisePropertyChanged("idBook");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bookShop", Namespace="http://schemas.datacontract.org/2004/07/ServiceBookShop")]
    public partial class bookShop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idBookField;
        
        private string nameBookField;
        
        private string authorBookField;
        
        private string categoryField;
        
        private System.Nullable<decimal> priceBookField;
        
        private string descriptionBookField;
        
        private string pathBookField;
        
        private string pathimagesField;
        
        private System.Collections.ObjectModel.ObservableCollection<BookShop.ServiceReference1.userBookShop> userBookShopsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBook {
            get {
                return this.idBookField;
            }
            set {
                if ((this.idBookField.Equals(value) != true)) {
                    this.idBookField = value;
                    this.RaisePropertyChanged("idBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameBook {
            get {
                return this.nameBookField;
            }
            set {
                if ((object.ReferenceEquals(this.nameBookField, value) != true)) {
                    this.nameBookField = value;
                    this.RaisePropertyChanged("nameBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string authorBook {
            get {
                return this.authorBookField;
            }
            set {
                if ((object.ReferenceEquals(this.authorBookField, value) != true)) {
                    this.authorBookField = value;
                    this.RaisePropertyChanged("authorBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> priceBook {
            get {
                return this.priceBookField;
            }
            set {
                if ((this.priceBookField.Equals(value) != true)) {
                    this.priceBookField = value;
                    this.RaisePropertyChanged("priceBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string descriptionBook {
            get {
                return this.descriptionBookField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionBookField, value) != true)) {
                    this.descriptionBookField = value;
                    this.RaisePropertyChanged("descriptionBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string pathBook {
            get {
                return this.pathBookField;
            }
            set {
                if ((object.ReferenceEquals(this.pathBookField, value) != true)) {
                    this.pathBookField = value;
                    this.RaisePropertyChanged("pathBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string pathimages {
            get {
                return this.pathimagesField;
            }
            set {
                if ((object.ReferenceEquals(this.pathimagesField, value) != true)) {
                    this.pathimagesField = value;
                    this.RaisePropertyChanged("pathimages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public System.Collections.ObjectModel.ObservableCollection<BookShop.ServiceReference1.userBookShop> userBookShops {
            get {
                return this.userBookShopsField;
            }
            set {
                if ((object.ReferenceEquals(this.userBookShopsField, value) != true)) {
                    this.userBookShopsField = value;
                    this.RaisePropertyChanged("userBookShops");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceBookShop")]
    public interface IServiceBookShop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/loginBook", ReplyAction="http://tempuri.org/IServiceBookShop/loginBookResponse")]
        System.Threading.Tasks.Task<BookShop.ServiceReference1.usersShop> loginBookAsync(string users, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/createLogin", ReplyAction="http://tempuri.org/IServiceBookShop/createLoginResponse")]
        System.Threading.Tasks.Task createLoginAsync(BookShop.ServiceReference1.usersShop u, string png, byte[] s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/checkEmail", ReplyAction="http://tempuri.org/IServiceBookShop/checkEmailResponse")]
        System.Threading.Tasks.Task<bool> checkEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/getFile", ReplyAction="http://tempuri.org/IServiceBookShop/getFileResponse")]
        System.Threading.Tasks.Task<byte[]> getFileAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/getAllbook", ReplyAction="http://tempuri.org/IServiceBookShop/getAllbookResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<BookShop.ServiceReference1.bookShop>> getAllbookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/getUserBook", ReplyAction="http://tempuri.org/IServiceBookShop/getUserBookResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<BookShop.ServiceReference1.userBookShop>> getUserBookAsync(string user, int idBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/buyBook", ReplyAction="http://tempuri.org/IServiceBookShop/buyBookResponse")]
        System.Threading.Tasks.Task<bool> buyBookAsync(int idBook, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/getAllCatalogy", ReplyAction="http://tempuri.org/IServiceBookShop/getAllCatalogyResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<string>> getAllCatalogyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookShop/createBook", ReplyAction="http://tempuri.org/IServiceBookShop/createBookResponse")]
        System.Threading.Tasks.Task createBookAsync(BookShop.ServiceReference1.bookShop b, byte[] p, string pdf, string im, byte[] i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBookShopChannel : BookShop.ServiceReference1.IServiceBookShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBookShopClient : System.ServiceModel.ClientBase<BookShop.ServiceReference1.IServiceBookShop>, BookShop.ServiceReference1.IServiceBookShop {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceBookShopClient() : 
                base(ServiceBookShopClient.GetDefaultBinding(), ServiceBookShopClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceBookShop.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBookShopClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceBookShopClient.GetBindingForEndpoint(endpointConfiguration), ServiceBookShopClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBookShopClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceBookShopClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBookShopClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceBookShopClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBookShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<BookShop.ServiceReference1.usersShop> loginBookAsync(string users, string password) {
            return base.Channel.loginBookAsync(users, password);
        }
        
        public System.Threading.Tasks.Task createLoginAsync(BookShop.ServiceReference1.usersShop u, string png, byte[] s) {
            return base.Channel.createLoginAsync(u, png, s);
        }
        
        public System.Threading.Tasks.Task<bool> checkEmailAsync(string email) {
            return base.Channel.checkEmailAsync(email);
        }
        
        public System.Threading.Tasks.Task<byte[]> getFileAsync(string path) {
            return base.Channel.getFileAsync(path);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<BookShop.ServiceReference1.bookShop>> getAllbookAsync() {
            return base.Channel.getAllbookAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<BookShop.ServiceReference1.userBookShop>> getUserBookAsync(string user, int idBook) {
            return base.Channel.getUserBookAsync(user, idBook);
        }
        
        public System.Threading.Tasks.Task<bool> buyBookAsync(int idBook, string user) {
            return base.Channel.buyBookAsync(idBook, user);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<string>> getAllCatalogyAsync() {
            return base.Channel.getAllCatalogyAsync();
        }
        
        public System.Threading.Tasks.Task createBookAsync(BookShop.ServiceReference1.bookShop b, byte[] p, string pdf, string im, byte[] i) {
            return base.Channel.createBookAsync(b, p, pdf, im, i);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceBookShop)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceBookShop)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:57354/ServiceBookShop.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServiceBookShopClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceBookShop);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServiceBookShopClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceBookShop);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IServiceBookShop,
        }
    }
}
